Squashed commit of the following: merge commit creating jraph_tool and rudamentary schema
commit dba991d464b2f433b4d787dc7d9ec404814c0830
Author: sophondetector <nateisgood@gmail.com>
Date:   Sat Sep 7 18:03:15 2024 -0400

    packaging everything into jraph_tool

commit d8fb48c6fea68ad9007ecaae6fc738d38eb8bbde
Author: sophondetector <nateisgood@gmail.com>
Date:   Sat Sep 7 17:44:55 2024 -0400

    make install python executable

commit e9f762891301cde73c0cd0040082f573b3c79e19
Author: sophondetector <nateisgood@gmail.com>
Date:   Sat Sep 7 17:36:46 2024 -0400

    get rid of non working sql send command

commit 78527851cfb8569fb599e496f8781e990abea143
Author: sophondetector <nateisgood@gmail.com>
Date:   Sat Sep 7 17:30:37 2024 -0400

    make CONN persistent in insert_data.py

commit a1a93405684de21ad510425601f0a4c1796a3860
Author: sophondetector <nateisgood@gmail.com>
Date:   Sat Sep 7 17:30:16 2024 -0400

    add check_pass to ndev

commit 6d80bd28e60f3c299ec32fd21662ce12f0724df2
Author: sophondetector <nateisgood@gmail.com>
Date:   Fri Sep 6 23:19:43 2024 -0400

    add get_pass to insert_data

commit f828026f603a5d68616e8b671b0cc857330a0d74
Author: sophondetector <nateisgood@gmail.com>
Date:   Fri Sep 6 18:28:32 2024 -0400

    ignore pycache and some working pyodbc code

commit b89efd30d62ea93fa24648e8a8bee13e43b657f0
Author: sophondetector <nateisgood@gmail.com>
Date:   Fri Sep 6 17:42:44 2024 -0400

    moving stuff from jraph_schema into portal because permissions

commit 176367f8e8ca1c85ed9ccd43bfafcedde3b7fcc7
Author: sophondetector <nateisgood@gmail.com>
Date:   Fri Sep 6 16:45:15 2024 -0400

    Remove data.json and begin creating jraph schema and fake init data

diff --git a/ndev b/ndev
--- a/ndev
+++ b/ndev
@@ -10,6 +10,13 @@ TEST_DATABASE="testdb"
 # $ ndev --help **prints all docstrings**
 # $ ndev build --help **prints build docstring**
 
+check_pass () {
+	if [[ ! -v JRAPH_SA_PASSWORD ]]; then
+		echo "\$JRAPH_SA_PASSWORD required!"
+		exit 1
+	fi
+}
+
 build () {
 	# TODO REDO using CONTAINERFILE
 	# TODO configgify msql setup options
@@ -24,7 +31,7 @@ build () {
 		--tty \
 		--publish-all \
 		--replace \
-		--volume="./portal/:/root/portal:z" \
+		--volume="./portal/:/root/portal:Z" \
 		"fedora:latest" \
 		"portal/install-sqlserver.sh"
 
@@ -45,7 +52,7 @@ build () {
 		--interactive \
 		--tty \
 		--publish-all \
-		--volume="./portal/:/root/portal:z" \
+		--volume="./portal/:/root/portal:Z" \
 		--name="$STAGE_TWO" \
 		--replace \
 		"$IMAGE_NAME"
@@ -56,18 +63,21 @@ start () {
 }
 
 test.init () {
+	check_pass
 	podman exec --interactive --tty \
 		$STAGE_TWO \
 		/opt/mssql-tools18/bin/sqlcmd \
 			-C -U sa -P $JRAPH_SA_PASSWORD \
-			-i portal/testdb-init.sql -o portal/testdb-init-output.out
+			-i portal/testdb-init.sql 
 }
 
 test () {
+	check_pass
 	podman exec --interactive --tty \
 		$STAGE_TWO \
 		/opt/mssql-tools18/bin/sqlcmd \
-			-C -U sa -P $JRAPH_SA_PASSWORD -d $TEST_DATABASE -Q "select * from dbo.Products"
+			-C -U sa -P $JRAPH_SA_PASSWORD -d $TEST_DATABASE \
+			-Q "select * from dbo.Products"
 }
 
 shell () {
@@ -79,10 +89,5 @@ jraph_client () {
 	podman exec --interactive --tty $STAGE_TWO \
 		/usr/bin/python portal/return_kml.py "$@"
 }
-
-clean () {
-	echo "not implemented" # TODO implement ./ndev clean
-}
-
 
 "$@"
